/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaSwing_projemPackage;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author M-ORMAN09
 */
public class YILDIZcafe_girisEkrani extends javax.swing.JFrame {

    
    
public Color beyaz = new Color(255,255,255);
public Color kirmizi = new Color(255,51,51);
public Color kirmizi2 = new Color(255,102,102);
public Color yesil = new Color(153,255,153);
public Color yesil2 = new Color(0,255,0);
public Color yesil3 = new Color(102,255,102);
public Color turkuaz = new Color(153,255,255);



public Icon foto1 = new ImageIcon(getClass().getResource("/javaSwing_fotoPackage/coffee-shop1.png"));
public Icon foto2 = new ImageIcon(getClass().getResource("/javaSwing_fotoPackage/coffee-shop.png"));
public Icon uyari0 = new ImageIcon(getClass().getResource("/javaSwing_fotoPackage/uyari_icon.png"));
public Icon info0 = new ImageIcon(getClass().getResource("/javaSwing_fotoPackage/info_icon.png"));
public Icon giris0 = new ImageIcon(getClass().getResource("/javaSwing_fotoPackage/giris_icon.png"));



    /**
     * Creates new form JavaSwing_projemJFrame
     */
    public YILDIZcafe_girisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_giris = new javax.swing.JPanel();
        jButton_menu = new javax.swing.JButton();
        jTextField_telefon = new javax.swing.JTextField();
        jTextField_istekBolumu = new javax.swing.JTextField();
        jLabel_cafeİsmi = new javax.swing.JLabel();
        jComboBox_masayıSeciniz = new javax.swing.JComboBox<>();
        jComboBox_hangiGün = new javax.swing.JComboBox<>();
        jComboBox_cocukSayisi = new javax.swing.JComboBox<>();
        jLabel_girisİkonu = new javax.swing.JLabel();
        jButton_kaydet = new javax.swing.JButton();
        jTextField_soyadi = new javax.swing.JTextField();
        jLabel_rezervasyonİsmi = new javax.swing.JLabel();
        jTextField_isim = new javax.swing.JTextField();
        jComboBox_bireySayisi = new javax.swing.JComboBox<>();
        jButton_cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel_giris.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_giris.setPreferredSize(new java.awt.Dimension(1520, 800));

        jButton_menu.setBackground(new java.awt.Color(153, 255, 255));
        jButton_menu.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jButton_menu.setText("MENÜ İÇİN BU ALANA TIKLAYINIZ..");
        jButton_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_menuMouseExited(evt);
            }
        });
        jButton_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menuActionPerformed(evt);
            }
        });

        jTextField_telefon.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jTextField_telefon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "TELEFON ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jTextField_telefon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_telefonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_telefonMouseExited(evt);
            }
        });

        jTextField_istekBolumu.setFont(new java.awt.Font("Serif", 3, 17)); // NOI18N
        jTextField_istekBolumu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ÎSTEK BÖLÜMÜ(zorunlu değil) ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 2, 14))); // NOI18N
        jTextField_istekBolumu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_istekBolumuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_istekBolumuMouseExited(evt);
            }
        });

        jLabel_cafeİsmi.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_cafeİsmi.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel_cafeİsmi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cafeİsmi.setText("YILDIZ CAFE    ");

        jComboBox_masayıSeciniz.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jComboBox_masayıSeciniz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "MASA 1", "MASA 2", "MASA 3", "MASA 4", "MASA 5" }));
        jComboBox_masayıSeciniz.setToolTipText("");
        jComboBox_masayıSeciniz.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MASA SEÇİMİ ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jComboBox_masayıSeciniz.setPreferredSize(new java.awt.Dimension(127, 27));
        jComboBox_masayıSeciniz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_masayıSecinizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_masayıSecinizMouseExited(evt);
            }
        });

        jComboBox_hangiGün.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jComboBox_hangiGün.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar" }));
        jComboBox_hangiGün.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "HANGİ GÜN ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jComboBox_hangiGün.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_hangiGünMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_hangiGünMouseExited(evt);
            }
        });

        jComboBox_cocukSayisi.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jComboBox_cocukSayisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "0 ÇOCUK", "1 ÇOCUK", "2 ÇOCUK", "3 ÇOCUK", "4 ÇOCUK" }));
        jComboBox_cocukSayisi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ÇOCUK SAYISI ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jComboBox_cocukSayisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_cocukSayisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_cocukSayisiMouseExited(evt);
            }
        });

        jLabel_girisİkonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaSwing_fotoPackage/coffee-shop.png"))); // NOI18N
        jLabel_girisİkonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_girisİkonuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_girisİkonuMouseExited(evt);
            }
        });

        jButton_kaydet.setBackground(new java.awt.Color(255, 51, 51));
        jButton_kaydet.setFont(new java.awt.Font("Serif", 3, 8)); // NOI18N
        jButton_kaydet.setText("KAYDET");
        jButton_kaydet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_kaydetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_kaydetMouseExited(evt);
            }
        });
        jButton_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kaydetActionPerformed(evt);
            }
        });

        jTextField_soyadi.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jTextField_soyadi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SOYİSİM", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jTextField_soyadi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_soyadiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_soyadiMouseExited(evt);
            }
        });

        jLabel_rezervasyonİsmi.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel_rezervasyonİsmi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_rezervasyonİsmi.setText("REZERVASYON İÇİN :");

        jTextField_isim.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jTextField_isim.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "İSİM", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jTextField_isim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_isimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_isimMouseExited(evt);
            }
        });

        jComboBox_bireySayisi.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jComboBox_bireySayisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1 KİŞİ", "2 KİŞİ", "3 KİŞİ", "4 KİŞİ", "5 KİŞİ" }));
        jComboBox_bireySayisi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "BİREY SAYISI ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 12))); // NOI18N
        jComboBox_bireySayisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_bireySayisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_bireySayisiMouseExited(evt);
            }
        });

        jButton_cikis.setBackground(new java.awt.Color(153, 255, 255));
        jButton_cikis.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jButton_cikis.setText("ÇIKIŞ İÇİN BU ALANA TIKLAYINIZ..");
        jButton_cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_cikisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_cikisMouseExited(evt);
            }
        });
        jButton_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_girisLayout = new javax.swing.GroupLayout(jPanel_giris);
        jPanel_giris.setLayout(jPanel_girisLayout);
        jPanel_girisLayout.setHorizontalGroup(
            jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_girisLayout.createSequentialGroup()
                .addContainerGap(443, Short.MAX_VALUE)
                .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_girisLayout.createSequentialGroup()
                        .addComponent(jLabel_girisİkonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_girisLayout.createSequentialGroup()
                                .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_girisLayout.createSequentialGroup()
                                        .addComponent(jComboBox_cocukSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jComboBox_hangiGün, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_girisLayout.createSequentialGroup()
                                        .addComponent(jComboBox_bireySayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jComboBox_masayıSeciniz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)
                                .addComponent(jButton_kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel_rezervasyonİsmi, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jTextField_soyadi)
                            .addComponent(jTextField_isim)
                            .addComponent(jTextField_telefon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_cafeİsmi, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)))
                    .addComponent(jTextField_istekBolumu)
                    .addGroup(jPanel_girisLayout.createSequentialGroup()
                        .addComponent(jButton_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanel_girisLayout.setVerticalGroup(
            jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_girisLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_girisLayout.createSequentialGroup()
                        .addComponent(jLabel_cafeİsmi)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel_rezervasyonİsmi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_girisLayout.createSequentialGroup()
                                .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_masayıSeciniz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_bireySayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_hangiGün, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_cocukSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jButton_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_girisİkonu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jTextField_istekBolumu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel_girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void jButton_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menuMouseEntered
        jButton_menu.setBackground(yesil3);    
    }//GEN-LAST:event_jButton_menuMouseEntered

    private void jButton_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menuMouseExited
        jButton_menu.setBackground(turkuaz);
    }//GEN-LAST:event_jButton_menuMouseExited

    
    
    private void jButton_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menuActionPerformed
        YILDIZcafe_menuEkrani menuEkrani = new YILDIZcafe_menuEkrani();
        menuEkrani.setVisible(true);
        this.setVisible(false);         
    }//GEN-LAST:event_jButton_menuActionPerformed

    
    
    private void jTextField_telefonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_telefonMouseEntered
        jTextField_telefon.setBackground(yesil);
    }//GEN-LAST:event_jTextField_telefonMouseEntered

    private void jTextField_telefonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_telefonMouseExited
        jTextField_telefon.setBackground(beyaz);
    }//GEN-LAST:event_jTextField_telefonMouseExited

    private void jTextField_istekBolumuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_istekBolumuMouseEntered
        jTextField_istekBolumu.setBackground(yesil);
    }//GEN-LAST:event_jTextField_istekBolumuMouseEntered

    private void jTextField_istekBolumuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_istekBolumuMouseExited
        jTextField_istekBolumu.setBackground(beyaz);
    }//GEN-LAST:event_jTextField_istekBolumuMouseExited

    private void jLabel_girisİkonuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_girisİkonuMouseEntered
        jLabel_girisİkonu.setIcon(foto1);
    }//GEN-LAST:event_jLabel_girisİkonuMouseEntered

    private void jLabel_girisİkonuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_girisİkonuMouseExited
        jLabel_girisİkonu.setIcon(foto2);
    }//GEN-LAST:event_jLabel_girisİkonuMouseExited

    private void jButton_kaydetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kaydetMouseEntered
        jButton_kaydet.setBackground(yesil2);
    }//GEN-LAST:event_jButton_kaydetMouseEntered

    private void jButton_kaydetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kaydetMouseExited
        jButton_kaydet.setBackground(kirmizi);
    }//GEN-LAST:event_jButton_kaydetMouseExited

    
    
    private void jButton_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kaydetActionPerformed
        if(jTextField_isim.getText().equals("")||(jTextField_soyadi.getText().equals(""))||(jTextField_telefon.getText().equals(""))||(jComboBox_bireySayisi.getSelectedItem().toString().equals("-"))||(jComboBox_cocukSayisi.getSelectedItem().toString().equals("-"))||(jComboBox_masayıSeciniz.getSelectedItem().toString().equals("-"))||(jComboBox_hangiGün.getSelectedItem().toString().equals("-"))){
            JOptionPane.showMessageDialog(this, "LÜTFEN BİLGİLERİNİZİ EKSİKSİZ GİRİNİZ.. ", "REZERVASYON ", 1, uyari0);
        }
        else if (jComboBox_masayıSeciniz.getSelectedItem().toString().equals("MASA 4")){
            JOptionPane.showMessageDialog(this, "MASA 4 REZERVE EDİLMİŞTİR, FARKLI BİR MASA SEÇİNİZ.. ", "REZERVASYON " , 1, info0);     
        }
        else{
            JOptionPane.showMessageDialog(this, "İŞLEM TAMAMLANDI.. ", "REZERVASYON ", 1, giris0);
            YILDIZcafe_menuEkrani menuEkrani = new YILDIZcafe_menuEkrani();
            menuEkrani.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton_kaydetActionPerformed

    
    
    private void jTextField_soyadiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_soyadiMouseEntered
        jTextField_soyadi.setBackground(yesil);
    }//GEN-LAST:event_jTextField_soyadiMouseEntered

    private void jTextField_soyadiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_soyadiMouseExited
        jTextField_soyadi.setBackground(beyaz);
    }//GEN-LAST:event_jTextField_soyadiMouseExited

    private void jTextField_isimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_isimMouseEntered
        jTextField_isim.setBackground(yesil);
    }//GEN-LAST:event_jTextField_isimMouseEntered

    private void jTextField_isimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_isimMouseExited
        jTextField_isim.setBackground(beyaz);
    }//GEN-LAST:event_jTextField_isimMouseExited

    private void jComboBox_hangiGünMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_hangiGünMouseExited
        jComboBox_hangiGün.setBackground(Color.WHITE);
    }//GEN-LAST:event_jComboBox_hangiGünMouseExited

    private void jComboBox_hangiGünMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_hangiGünMouseEntered
        jComboBox_hangiGün.setBackground(Color.GREEN);
    }//GEN-LAST:event_jComboBox_hangiGünMouseEntered

    private void jComboBox_masayıSecinizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_masayıSecinizMouseExited
        jComboBox_masayıSeciniz.setBackground(Color.WHITE);
    }//GEN-LAST:event_jComboBox_masayıSecinizMouseExited

    private void jComboBox_masayıSecinizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_masayıSecinizMouseEntered
        jComboBox_masayıSeciniz.setBackground(Color.GREEN);
    }//GEN-LAST:event_jComboBox_masayıSecinizMouseEntered

    private void jComboBox_cocukSayisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_cocukSayisiMouseExited
        jComboBox_cocukSayisi.setBackground(Color.WHITE);
    }//GEN-LAST:event_jComboBox_cocukSayisiMouseExited

    private void jComboBox_cocukSayisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_cocukSayisiMouseEntered
        jComboBox_cocukSayisi.setBackground(Color.GREEN);
    }//GEN-LAST:event_jComboBox_cocukSayisiMouseEntered

    private void jComboBox_bireySayisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_bireySayisiMouseExited
        jComboBox_bireySayisi.setBackground(Color.WHITE);
    }//GEN-LAST:event_jComboBox_bireySayisiMouseExited

    private void jComboBox_bireySayisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_bireySayisiMouseEntered
        jComboBox_bireySayisi.setBackground(Color.GREEN);
    }//GEN-LAST:event_jComboBox_bireySayisiMouseEntered

    private void jButton_cikisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cikisMouseEntered
        jButton_cikis.setBackground(kirmizi2);
    }//GEN-LAST:event_jButton_cikisMouseEntered

    private void jButton_cikisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cikisMouseExited
        jButton_cikis.setBackground(turkuaz);
    }//GEN-LAST:event_jButton_cikisMouseExited

    private void jButton_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cikisActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_cikisActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YILDIZcafe_girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YILDIZcafe_girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YILDIZcafe_girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YILDIZcafe_girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YILDIZcafe_girisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cikis;
    private javax.swing.JButton jButton_kaydet;
    private javax.swing.JButton jButton_menu;
    private javax.swing.JComboBox<String> jComboBox_bireySayisi;
    private javax.swing.JComboBox<String> jComboBox_cocukSayisi;
    private javax.swing.JComboBox<String> jComboBox_hangiGün;
    private javax.swing.JComboBox<String> jComboBox_masayıSeciniz;
    private javax.swing.JLabel jLabel_cafeİsmi;
    private javax.swing.JLabel jLabel_girisİkonu;
    private javax.swing.JLabel jLabel_rezervasyonİsmi;
    private javax.swing.JPanel jPanel_giris;
    private javax.swing.JTextField jTextField_isim;
    private javax.swing.JTextField jTextField_istekBolumu;
    private javax.swing.JTextField jTextField_soyadi;
    private javax.swing.JTextField jTextField_telefon;
    // End of variables declaration//GEN-END:variables
}
